package com.adrip.mayordomo.commands;

public enum CommandType {
	CREATE, STATUS, HELP, CHANNELCAPACITY, CHANNELNAME, ADMINHELP, INVOKECREATE, SETINFOCHANNEL, SETUSECHANNEL,
	SETPREFIX, ENABLE, DISABLE, TOGGLE, UNIQUE,
}
